#ifndef _CONFIG_H_
#define _CONFIG_H_

#define F_CPU (8000000UL)
#define CONFIG_SWUART_RX_BUF (20)
#define CONFIG_SWUART_TX_BUF (20)
#define CONFIG_UART_RX_BUF (20)
#define CONFIG_UART_TX_BUF (20)
#define CONFIG_DEBUG_BAUDRATE (2400)
#define CONFIG_GSM_BAUDRATE (9600)

#endif
